name: Build and Push Docker Image (Single Service)

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      version:
        required: false
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: depot/setup-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract short SHA
        id: sha
        run: echo "short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Resolve manifest key and version
        id: manifest
        run: |
          source .ci/manifest-utils.sh

          SERVICE="${{ inputs.service }}"
          MANIFEST_KEY=$(resolve_manifest_key "$SERVICE")
          VERSION=$(get_manifest_version "$SERVICE")
          SERVICE_NAME=$(service_name_from_path "$MANIFEST_KEY")

          echo "Resolved manifest key: $MANIFEST_KEY"
          echo "Resolved version: $VERSION"
          echo "Resolved service name: $SERVICE_NAME"

          echo "key=$MANIFEST_KEY" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "name=$SERVICE_NAME" >> $GITHUB_OUTPUT

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ inputs.service }}
          tags: |
            type=ref,event=pr
            type=sha,format=short
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=v${{ steps.manifest.outputs.version }},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=raw,value=v${{ steps.manifest.outputs.version }}-${{ steps.sha.outputs.short }}

      - name: Build and push with Depot
        uses: depot/build-push-action@v1
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: project=${{ inputs.service }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
